# NumPy

In [ ]:
from numpy import array
from numpy import empty
from numpy import zeros
from numpy import ones
from numpy import vstack
from numpy import hstack

## Introduction to NumPy Arrays

### NumPy N-dimensional Array

In [ ]:
my_list = [1.0, 2.0, 3.0]

In [ ]:
my_array = array(my_list)

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
print(my_array)

[1. 2. 3.]


In [ ]:
print(my_array.shape, my_array.dtype)

(3,) float64


### Functions to Create Arrays

**Empty**

In [ ]:
my_array = empty([3,3])
my_array

array([[6.94676088e-310, 6.94676088e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [1.23075756e-312, 2.42092166e-322, 6.94676088e-310]])

**Zeros**

In [ ]:
my_array = zeros([2,5])
my_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Ones**

In [ ]:
my_array = ones([4,2])
my_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Combining Arrays

**Vertical Stack**

In [ ]:
a1 = array([1,2,3])
print(a1)

[1 2 3]


In [ ]:
a2 = array([4,5,6])
print(a2)

[4 5 6]


In [ ]:
a3 = vstack((a1,a2))
print(a3)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a3.shape)

(2, 3)


**Horizontal Stack**

In [ ]:
a1 = array([1,2,3])

In [ ]:
a2 = array([4,5,6])

In [ ]:
a3 = hstack((a1,a2))
print(a3)

[1 2 3 4 5 6]


In [ ]:
print(a3.shape)

(6,)


## Index, Slice and Reshape NumPy Arrays

### From List to Arrays

**One-Dimensional List to Array**

In [ ]:
data = [11,12,33,47]
print(data)

[11, 12, 33, 47]


In [ ]:
type(data)

list

In [ ]:
data_array = array(data)
print(data_array)

[11 12 33 47]


In [ ]:
type(data_array)

numpy.ndarray

In [ ]:
data_array.shape

(4,)

**Two-Dimensional List of Lists to Array**

In [ ]:
data = [[11,22],
       [33, 44],
       [55, 66]]

In [ ]:
print(data)

[[11, 22], [33, 44], [55, 66]]


In [ ]:
data_array = array(data)

In [ ]:
print(data_array)

[[11 22]
 [33 44]
 [55 66]]


In [ ]:
type(data_array)

numpy.ndarray

In [ ]:
data_array.shape

(3, 2)

### Array Indexing

**One-Dimensional Indexing**

In [ ]:
data = array([11,22,33,44,55])

In [ ]:
data[0]

11

In [ ]:
data[4]

55

In [ ]:
#data[5]

In [ ]:
data[-1]

55

In [ ]:
data[-5]

11

**Two-Dimensional Indexing**

In [ ]:
data = array([[11,22],
            [33, 44],
            [55, 66]])

In [ ]:
data[0,0]

11

In [ ]:
data[0, ]

array([11, 22])

### Array Slicing

data [from : to]

**One-Dimensional Slicing**

In [ ]:
data = array([11,22,33,44,55])

In [ ]:
print(data[:])

[11 22 33 44 55]


In [ ]:
print(data[0:3])

[11 22 33]


In [ ]:
print(data[-2:])

[44 55]


#### Two-Dimensional Slicing

**Split Input and Output Features**

X = [: , : -1] this is the input

y = [: , -1] this is the output

In [ ]:
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

In [ ]:
X, y = data[: , :-1], data[:, -1]

In [ ]:
print(X)

[[11 22]
 [44 55]
 [77 88]]


In [ ]:
print(y)

[33 66 99]


**Split Train and Test Rows**

train = data [ : split , :]

test = data [split : , :]

In [ ]:
data = array([[11,22,33],
             [44,55,66],
             [77,88,99]])

In [ ]:
split = 2

In [ ]:
train, test = data[:split, :], data[split:,:]

In [ ]:
train

array([[11, 22, 33],
       [44, 55, 66]])

In [ ]:
test

array([[77, 88, 99]])

### Array Reshaping

**Data shape**

In [ ]:
data = array([11,22,33,44])
data.shape

(4,)

In [ ]:
data = array([[11,22],
             [33,44],
             [55,66]])
data.shape

(3, 2)

In [ ]:
data.shape[0]

3

In [ ]:
data.shape[1]

2

**Reshape 1D to 2D Array**

data = data.reshape( (data.shape[0] , 1) )

In [ ]:
data = array([11,22,33,44,55])
data.shape

(5,)

In [ ]:
data = data.reshape((data.shape[0], 1))
data.shape

(5, 1)

**Reshape 2D to 3D Array**

data = data.reshape( (data.shape[0], data.shape[1], 1) )

In [ ]:
data = array([[11,22],
             [33,44],
             [55,66]])
data.shape

(3, 2)

In [ ]:
data = data.reshape((data.shape[0], data.shape[1], 1))
data.shape

(3, 2, 1)

## NumPy Array Broadcasting

### Broadcasting in NumPy

**Scalar and One-Dimensional Array**

a = [a1, a2, a3] \
b \
c = a + b \
c = [a1+b, a2+b, a3+b]

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = 2
print(b)

2


In [ ]:
c = a + b
print(c)

[3 4 5]


**Scalar and Two-Dimensional Array**

In [ ]:
a = array([[1,2,3],
         [1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [ ]:
b = 2

In [ ]:
c = a + b

In [ ]:
print(c)

[[3 4 5]
 [3 4 5]]


**One-Dimensional and Two-Dimensional Arrays**

In [ ]:
a = array([[1,2,3],
          [1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [ ]:
b = array([4,5,6])

In [ ]:
c = a + b

In [ ]:
print(c)

[[5 7 9]
 [5 7 9]]


### Limitations of Broadcasting

A.shape = (2 x 3)\
b.shape = (3)

A.shape = (2 x 3)\
b.shape = (1 x 3)

A.shape = (2 x 3)\
b.shape = (1)

A.shape = (2 x 3)\
b.shape = (1 x 1)

A.shape = (2 x 3)\
b.shape = (1 x 2)

In [ ]:
a = array([[1,2,3],
          [1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [ ]:
b = array([1,2])
print(b)

[1 2]


In [ ]:
#c = a + b