# Matrices

In [ ]:
from numpy import inf
from numpy import array
from numpy import identity
from numpy import trace
from numpy import count_nonzero
from numpy import tensordot
from numpy import tril, triu, diag
from numpy.linalg import norm, inv, det, matrix_rank
from scipy.sparse import csr_matrix

## Vectors and Vector Arithmetic

**Defining a Vector**

In [ ]:
vector = array([1,2,3])
print(vector)

[1 2 3]


### Vector Arithmetic

**Vector Addition**

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = array([4,5,6])
print(b)

[4 5 6]


In [ ]:
c = a + b
print(c)

[5 7 9]


**Vector Subtraction**

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = array([0.5,0.5,0.5])
print(b)

[0.5 0.5 0.5]


In [ ]:
c = a - b
print(c)

[0.5 1.5 2.5]


**Vector Multiplication**

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = array([1,2,3])
print(b)

[1 2 3]


In [ ]:
c = a*b
print(c)

[1 4 9]


**Vector Division**

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = array([1,2,3])
print(b)

[1 2 3]


In [ ]:
c = a/b
print(c)

[1. 1. 1.]


### Vector Dot Product

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = array([1,2,3])
print(b)

[1 2 3]


In [ ]:
c = a.dot(b)
print(c)

14


### Vector-Scalar Multiplication

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = 0.5
print(b)

0.5


In [ ]:
c = b*a
print(c)

[0.5 1.  1.5]


## Vector Norms

In [ ]:
a = array([1,2,3])
print(a)

[1 2 3]


**Vector L1 Norm**

In [ ]:
l1 = norm(a, 1)
print(l1)

6.0


**Vector L2 Norm**

In [ ]:
l2 = norm(a)
print(l2)

3.7416573867739413


**Vector Max Norm**

In [ ]:
maxnorm = norm(a,inf)
print(maxnorm)

3.0


## Matrices and Matrix Arithmetic

**Defining a Matrix**

In [ ]:
A = array([[1,2,3],
          [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Matrix Arithmetic

In [ ]:
A = array([[1,2,3],
         [4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
B = array([[1,2,3],
          [4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


**Matrix Addition**

In [ ]:
C = A + B
print(C)

[[ 2  4  6]
 [ 8 10 12]]


**Matrix Subtraction**

In [ ]:
C = A - B
print(C)

[[0 0 0]
 [0 0 0]]


**Matrix Multiplication (Hadamard Product)**

In [ ]:
C = A *B
print(C)

[[ 1  4  9]
 [16 25 36]]


**Matrix Division**

In [ ]:
C = A / B
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


### Matrix-Matrix Multiplication

In [ ]:
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
B = array([
    [1,2],
    [3,4]])
print(B)

[[1 2]
 [3 4]]


In [ ]:
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]
 [23 34]]


In [ ]:
D = A @ B
print(D)

[[ 7 10]
 [15 22]
 [23 34]]


### Matrix-Vector Multiplication

In [ ]:
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
b = array([0.5, 0.5])
print(b)

[0.5 0.5]


In [ ]:
C = A.dot(b)
print(C)

[1.5 3.5 5.5]


### Matrix-Scalar Multiplication

In [ ]:
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
b = 0.5
print(b)

0.5


In [ ]:
C = A*b
print(C)

[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


## Types of Matrices

**Square Matrix**

**Symmetric Matrix**

**Triangular Matrix**

In [ ]:
M = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
lower = tril(M)
print(lower)

[[1 0 0]
 [1 2 0]
 [1 2 3]]


In [ ]:
upper = triu(M)
print(upper)

[[1 2 3]
 [0 2 3]
 [0 0 3]]


**Diagonal Matrix**

In [ ]:
M = array([
    [1,2,3],
    [1,2,3],
    [1,2,3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
d = diag(M)
print(d)

[1 2 3]


In [ ]:
D = diag(d)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Identity Matrix**

In [ ]:
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Orthogonal Matrix**

In [ ]:
Q = array([
    [1,0],
    [0,-1]])
print(Q)

[[ 1  0]
 [ 0 -1]]


In [ ]:
V = inv(Q)
print(V)

[[ 1.  0.]
 [-0. -1.]]


In [ ]:
print(Q.T)

[[ 1  0]
 [ 0 -1]]


In [ ]:
I = Q.dot(Q.T)
print(I)

[[1 0]
 [0 1]]


## Matrix Operations

**Transpose**

In [ ]:
A = array([
    [1,2],
    [3,4],
    [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
C = A.T
print(C)

[[1 3 5]
 [2 4 6]]


**Inverse**

In [ ]:
A = array([
    [1.0, 2.0],
    [3.0, 4.0]])
print(A)

[[1. 2.]
 [3. 4.]]


In [ ]:
B = inv(A)
print(B)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
I = A.dot(B)
print(I)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


**Trace**

In [ ]:
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
B = trace(A)
print(B)

15


**Determinant**

In [ ]:
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,99]])
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


In [ ]:
B = det(A)
print(B)

-269.99999999999983


**Rank**

In [ ]:
v1 = array([1,2,3])
print(v1)

[1 2 3]


In [ ]:
print(matrix_rank(v1))

1


In [ ]:
v2 = array([0,0,0,0,0])
print(v2)

[0 0 0 0 0]


In [ ]:
print(matrix_rank(v2))

0


In [ ]:
M0 = array([
    [0,0],
    [0,0]])
print(M0)

[[0 0]
 [0 0]]


In [ ]:
print(matrix_rank(M0))

0


In [ ]:
M1 = array([
    [1,2],
    [1,2]])
print(M1)

[[1 2]
 [1 2]]


In [ ]:
print(matrix_rank(M1))

1


In [ ]:
M2 = array([
    [1,2],
    [3,4]])
print(M2)

[[1 2]
 [3 4]]


In [ ]:
print(matrix_rank(M2))

2


## Sparse Matrices

**Sparse Matrices in Python**

In [ ]:
A = array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]])
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [ ]:
S = csr_matrix(A)
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [ ]:
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [ ]:
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

0.7222222222222222


## Tensors and Tensor Arithmetic

### Tensors in Python

In [ ]:
T = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
print(T.shape)

(3, 3, 3)


### Tensor Arithmetic

**Tensor Addition**

In [ ]:
A = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

B = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


**Tensor Subtraction**

In [ ]:
A = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

B = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


**Tensor Hadamard Product**

In [ ]:
A = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

B = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


**Tensor Division**

In [ ]:
A = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

B = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

C = A / B
print(C)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


### Tensor Product

In [ ]:
A = array([1,2])
B = array([3,4])

In [ ]:
C = tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]
